name: xcoin2
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: 6.0.5
  dart_json_mapper: 2.2.7+1
  property_change_notifier: 0.3.0

  intl: 0.17.0
  hive_flutter: 1.1.0

  retrofit: 4.0.1
  logger: any
  dio: 5.0.0
  dio_http2_adapter:
  jwt_decode: 0.3.1

  auto_route: 5.0.4
  reflectable: 4.0.4
  flutter_flavor: ^3.1.1
  platform_device_id: ^1.0.1

  permission_handler: 10.2.0
  device_info_plus: 8.1.0
  package_info_plus: 3.0.3

  fluttertoast: 8.1.3
  adaptive_dialog: 1.8.2
  flutter_svg: 2.0.0+1
  cached_network_image: 3.2.3
  animate_do: 3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.3.3
  auto_route_generator: 5.0.3
  retrofit_generator: 5.0.0
  flutter_lints: 2.0.1

  

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/translations/
  
  fonts:
    - family: robotoBlack
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf

    - family: robotoBlackItalic
      fonts:
        - asset: assets/fonts/Roboto-BlackItalic.ttf

    - family: robotoBold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf

    - family: robotoBoldItalic
      fonts:
        - asset: assets/fonts/Roboto-BoldItalic.ttf

    - family: robotoItalic
      fonts:
        - asset: assets/fonts/Roboto-Italic.ttf

    - family: robotoLight
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf

    - family: robotoLightItalic
      fonts:
        - asset: assets/fonts/Roboto-LightItalic.ttf

    - family: robotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf

    - family: robotoMediumItalic
      fonts:
        - asset: assets/fonts/Roboto-MediumItalic.ttf

    - family: robotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: robotoThin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf

    - family: robotoThinItalic
      fonts:
        - asset: assets/fonts/Roboto-ThinItalic.ttf
